-- 코드를 입력하세요
#SELECT MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
#GROUP BY MONTH(A.START_DATE), A.CAR_ID
#ORDER BY MONTH(A.START_DATE) ASC, CAR_ID DESC

SELECT MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
INNER JOIN 
(
    SELECT B.CAR_ID AS BKEY, COUNT(*) AS COUNT FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
    WHERE 8<= MONTH(B.START_DATE) AND MONTH(B.START_DATE)<=10
    GROUP BY B.CAR_ID
    HAVING COUNT >= 5 
) AS B
ON A.CAR_ID = B.BKEY
WHERE 8<=MONTH(A.START_DATE) AND MONTH(A.START_DATE) <=10
GROUP BY MONTH, A.CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC