WITH RECURSIVE GenerationCTE AS (
    SELECT ID AS ID, PARENT_ID AS PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID AS ID, e.PARENT_ID AS PARENT_ID, g.GENERATION + 1 AS GENERATION FROM ECOLI_DATA e
    JOIN GenerationCTE AS g ON e.PARENT_ID = g.ID
)
SELECT COUNT(*) AS COUNT, A.GENERATION FROM GenerationCTE AS A
WHERE A.ID NOT IN 
(
    SELECT PARENT_ID FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION


