SELECT A.ID, CASE
    WHEN A.SIZE_OF_COLONY BETWEEN 0 AND 100 THEN 'LOW'
    WHEN A.SIZE_OF_COLONY BETWEEN 101 AND 1000 THEN 'MEDIUM'
    WHEN A.SIZE_OF_COLONY > 1000 THEN 'HIGH'
    END AS SIZE FROM ECOLI_DATA AS A
ORDER BY A.ID
    