SELECT CASE
    WHEN MONTH(A.DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
    WHEN MONTH(A.DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
    WHEN MONTH(A.DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
    ELSE '4Q'
    END AS QUARTER, 
COUNT(*) AS ECOLI_COUNT FROM ECOLI_DATA AS A
GROUP BY QUARTER
ORDER BY QUARTER