SELECT DISTINCT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME FROM DEVELOPERS AS A
LEFT JOIN SKILLCODES AS B
ON A.SKILL_CODE & B.CODE = A.SKILL_CODE OR A.SKILL_CODE & B.CODE = B.CODE
WHERE B.CATEGORY = 'Front End'
ORDER BY A.ID