SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS
WHERE ID IN 
(
    SELECT DISTINCT A.ID FROM DEVELOPERS AS A
    INNER JOIN SKILLCODES AS B
    ON A.SKILL_CODE & B.CODE = A.SKILL_CODE OR A.SKILL_CODE & B.CODE = B.CODE
    WHERE 'Front End' = B.CATEGORY
)
ORDER BY ID


