SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS
INNER JOIN SKILLCODES
ON (DEVELOPERS.SKILL_CODE & SKILLCODES.CODE) <> 0
WHERE SKILLCODES.NAME = 'Python' OR SKILLCODES.NAME = 'C#'
ORDER BY ID

