SELECT B.YEAR AS YEAR, B.MAX-A.SIZE_OF_COLONY AS YEAR_DEV, A.ID AS ID FROM ECOLI_DATA AS A
LEFT JOIN 
(
SELECT MAX(SIZE_OF_COLONY) AS MAX, YEAR(DIFFERENTIATION_DATE) AS YEAR FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV ASC





