SELECT C.ID, D.FISH_NAME, D.LENGTH FROM FISH_INFO AS C
INNER JOIN 
(
SELECT A.FISH_TYPE, B.FISH_NAME, MAX(LENGTH) AS LENGTH FROM FISH_INFO AS A
LEFT JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY A.FISH_TYPE, B.FISH_NAME 
) AS D
ON C.FISH_TYPE = D.FISH_TYPE AND C.LENGTH = D.LENGTH
ORDER BY C.ID