SELECT A.DEPT_ID, A.DEPT_NAME_EN, ROUND(B.AVG_SAL) AS AVG_SAL FROM HR_DEPARTMENT AS A
INNER JOIN 
(
    SELECT DEPT_ID, AVG(SAL) AS AVG_SAL FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) AS B
ON A.DEPT_ID = B.DEPT_ID
ORDER BY AVG_SAL DESC