SELECT COUNT(*) AS FISH_COUNT, MAX(A.LENGTH) AS MAX_LENGTH, A.FISH_TYPE FROM FISH_INFO AS A
INNER JOIN 
(
SELECT FISH_TYPE AS FISH_TYPE, AVG(LENGTH) AS AVERAGE FROM FISH_INFO
GROUP BY FISH_TYPE
) AS B
ON A.FISH_TYPE = B.FISH_TYPE AND B.AVERAGE >= 33
GROUP BY A.FISH_TYPE
ORDER BY A.FISH_TYPE