-- 코드를 입력하세요
SELECT A.MEMBER_ID, A.MEMBER_NAME, A.GENDER, DATE_FORMAT(A.DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH FROM MEMBER_PROFILE AS A
WHERE A.TLNO IS NOT NULL AND A.GENDER = 'W' AND MONTH(A.DATE_OF_BIRTH) = '3'
ORDER BY A.MEMBER_ID